import json
from pathlib import Path
from datetime import datetime, timezone

WORKFLOW_FILE = Path("data/workflow_history.json")


def save_workflow(state):
    history = []

    if WORKFLOW_FILE.exists():
        try:
            history = json.loads(
                WORKFLOW_FILE.read_text(encoding="utf-8")
            )
        except (json.JSONDecodeError, OSError):
            history = []

    # Prevent accidental RUN-ID reuse if records were removed.
    existing_numbers = []

    for record in history:
        record_id = str(record.get("id", ""))

        if record_id.startswith("RUN-"):
            try:
                existing_numbers.append(
                    int(record_id.split("-")[1])
                )
            except (ValueError, IndexError):
                pass

    next_number = max(existing_numbers, default=0) + 1

    record = {
        "id": f"RUN-{next_number:04d}",
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "state": state.to_dict()
    }

    history.append(record)

    WORKFLOW_FILE.parent.mkdir(parents=True, exist_ok=True)

    WORKFLOW_FILE.write_text(
        json.dumps(
            history,
            indent=2,
            ensure_ascii=False,
            default=str
        ),
        encoding="utf-8"
    )

    return record


def list_workflows():
    if not WORKFLOW_FILE.exists():
        return []

    try:
        return json.loads(
            WORKFLOW_FILE.read_text(encoding="utf-8")
        )
    except (json.JSONDecodeError, OSError):
        return []


def search_workflows(query: str, limit: int = 5):
    """
    Search previous workflow records for relevant text.

    Searches only information that LIFEOPS previously stored.
    Results are ranked by the number of matching query terms.

    No new facts are generated by this function.
    """

    if not query or not query.strip():
        return []

    workflows = list_workflows()

    if not workflows:
        return []

    query_terms = {
        term.lower()
        for term in query.split()
        if term.strip()
    }

    if not query_terms:
        return []

    results = []

    for workflow in workflows:
        state = workflow.get("state", {})

        searchable_parts = [
            state.get("request", ""),
            state.get("plan", ""),
            state.get("priorities", ""),
            state.get("research", ""),
            state.get("action", ""),
            state.get("verification", ""),
            state.get("report", "")
        ]

        searchable_text = " ".join(
            str(part)
            for part in searchable_parts
            if part is not None
        ).lower()

        matched_terms = [
            term
            for term in query_terms
            if term in searchable_text
        ]

        if not matched_terms:
            continue

        results.append({
            "id": workflow.get("id"),
            "timestamp": workflow.get("timestamp"),
            "match_count": len(matched_terms),
            "matched_terms": sorted(matched_terms),
            "state": state
        })

    results.sort(
        key=lambda item: (
            item["match_count"],
            item.get("timestamp", "")
        ),
        reverse=True
    )

    return results[:max(1, limit)]